services:
  postgres:
    image: postgres:16-alpine
    container_name: iot_postgres
    environment:
      POSTGRES_DB: iot_gateway_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SecretPassword123!
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: iot_mosquitto
    ports:
      - "1883:1883"   # Porta MQTT standard (senza TLS per ora)
      - "8883:8883"   # Porta MQTT sicura con mTLS (Fase 3)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

volumes:
  postgres_data: